### ISSUE TITLE
I recommend renaming your branch to main

### ISSUE THREAD

**Issue by samrocketman** [leklachu/endless-sky-syndicate#1]
main is now a fairly standard name for branches on GitHub repos.

**Comment by samrocketman** [comment]
Here's how you can do that.

```
git fetch origin
git push origin refs/remotes/origin/release:refs/heads/main
```

You can then switch your default branch in repository settings.

You can delete the release branch with

```
git push origin :refs/heads/release
```

**Comment by leklachu** [comment]
I've been running the default `master`, just hosting `release` to hide notes on the campaign while in development. So I've pushed master now. (As to `main`: I'm old... old inside, at least - and used to 'master' in computing. My closest real-world experience of slavery has no use of the term master, and I don't come from America, so I don't feel the associations. If it happens you feel strongly on on this, I'm happy to take your advice and rename to `main` :-)  )

**Comment by samrocketman** [comment]
I'm fine with master branch.  I don't associate the branch name with slavery, either.  I do tend to use different terminology for distributed computing rather than the old master-slave compute term in practice.
