### ISSUE TITLE
Do you plan to pull request into vanilla?

### ISSUE THREAD

**Issue by samrocketman** [leklachu/endless-sky-syndicate#10]
If not do you mind someone else doing it while preserving your authorship?

**Comment by leklachu** [comment]
Hey, I'm really sorry, was busy and meant to get to it 'soon'...

Thanks for the reminder. I'll try and sort it today. Otherwise (and even so), yes, I'm very happy for others to, whether someone having that power in this repo, or through a fork.

**Comment by leklachu** [comment]
Done :-)

**Comment by samrocketman** [comment]
Hi @leklachu what I meant was contribute the syndicate story to Endless Sky (the core game) instead of keeping it a plugin.

**Comment by leklachu** [comment]
Oh! I'd love for this to be part of main Endless Sky, but when I first mentioned it, Amazinite said he's already planning a Syndicate storyline, and I took that to mean this one doesn't have a place.

**Comment by leklachu** [comment]
This could still be an alternate start in vanilla, if there's interest for it. There's several things that need touching up for it to be ready, but if it's going to go into vanilla I'd be happy to put the work into that. Perhaps we could make a draft PR and see? Would you like to help with that?

**Comment by samrocketman** [comment]
I think you should open a PR.  There has been no indication of syndicate story coming any time soon and your work does a great job providing syndicate store in a way that melds nice with the core story.

**Comment by leklachu** [comment]
Okay, PR at https://github.com/endless-sky/endless-sky/pull/8364

Thanks for the encouragement! Did you play this right through? I take it you enjoyed it, else you wouldn't be recommending it for vanilla!

**Comment by samrocketman** [comment]
I did and I liked it
