### ISSUE TITLE
Feature: Class C Protector

### ISSUE THREAD

**Issue by ziproot** [leklachu/endless-sky-syndicate#30]
From https://github.com/endless-sky/endless-sky/issues/5766:
> Given that the description of the Barb specifically calls out the fact that the Syndicate does not produce a carrier, I think that the Class C Protector would make an excellent mission ship to have unlocked at some point during the Syndicate campaign. Perhaps have an up-armored, up-shielded carrier version of the Protector that unlocks at roughly the same point in the Syndicate campaign as the Dreadnought in the FW story, and presumably around the same point as when the Carrier would be unlocked in the Navy campaign.

**Comment by leklachu** [comment]
That's cool. Thanks for pointing it out here.

So, if adapting this story to a main Syndicate campaign goes ahead, that sounds a great idea to write in, but I'd better not be the one to design the ship itself as I'm terrible at game balancing, especially for combat!

**Comment by ziproot** [comment]
OK, fair enough.
