### ISSUE TITLE
Replace LICENSE with a valid LICENSE

### ISSUE THREAD

**Issue by samrocketman** [leklachu/endless-sky-syndicate#5]
You have disclosed your license which is generally okay but it is more standard for you to include the full license text.  It helps contributors quickly know the license used.  I can open a pull request for this.

**Comment by leklachu** [comment]
Well, this sent me down a rabbit-hole of licensing! I prefer to release my stuff to public domain unless there's particular reason otherwise... but of course I can't release the whole work when part of it is copyright by someone else! I think the solution I've got fixes that.
